### ISSUE TITLE
we need a server javascript file

### ISSUE THREAD

**Issue by shendude** [Lollipop-Bandana/Lollipop-Bandana#2]
someone write server.js please

**Comment by mjstromberg** [comment]
good call @shendude

**Comment by mjstromberg** [comment]
@shendude I was actively working on this. Let's discuss

**Comment by shendude** [comment]
incredible :)

**Comment by mjstromberg** [comment]
I was also totally kidding, but it's good to hear from you!

**Comment by shendude** [comment]
lol ya i figured haha. Hope things are going well!
